/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface IconButtonProps {
  src: string;
  alt: string;
}

const IconButton: React.FC<IconButtonProps> = ({ src, alt }) => {
  return (
    <button className="flex overflow-hidden gap-2 justify-center items-center px-2.5 w-10 h-10 rounded-xl bg-stone-200 max-w-[480px] min-h-[40px]">
      <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0">
        <img
          loading="lazy"
          src={src}
          className="object-contain flex-1 w-5 aspect-square"
          alt={alt}
        />
      </div>
    </button>
  );
};

export default IconButton;
