/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ProfileImageProps {
  src: string;
  alt: string;
}

const ProfileImage: React.FC<ProfileImageProps> = ({ src, alt }) => {
  return (
    <img
      loading="lazy"
      src={src}
      className="object-contain shrink-0 w-10 rounded-3xl aspect-square"
      alt={alt}
    />
  );
};

export default ProfileImage;
