/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Category, { CategoryProps } from "./Category";

const CategoriesMenu: React.FC = () => {
  const categories: CategoryProps[] = [
    { title: "Appetizers", href: "/appetizers" },
    { title: "Main Courses", href: "/main-courses" },
    { title: "Desserts", href: "/desserts" },
    { title: "Beverages", href: "/beverages" },
    { title: "Snacks", href: "/snacks" },
  ]

  return (
    <aside className="flex overflow-hidden flex-col w-80 min-w-[240px]">
      {categories.map((category, index) => (
        <Category key={index} title={category.title} href={category.href} />
      ))}
    </aside>
  );
};

export default CategoriesMenu;
