/**
 * This code was generated by Builder.io.
 */
import React from "react";

export interface CategoryProps {
  title: string;
  href: string;
}

const Category: React.FC<CategoryProps> = ({ title, href }) => {
  return (
    <section className="flex gap-4 items-center px-4 w-full whitespace-nowrap bg-stone-50 min-h-[56px]">
      <a 
        href={href}
        className="overflow-hidden flex-1 shrink self-stretch my-auto w-full">
        {title}
      </a>
    </section>
  );
};

export default Category;
