/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ReviewBarProps {
  rating: number;
  percentage: number;
}

const ReviewBar: React.FC<ReviewBarProps> = ({ rating, percentage }) => {
  return (
    <div className="flex flex-1 mt-3 text-sm whitespace-nowrap size-full">
      <div className="w-5 text-stone-900">{rating}</div>
      <div className="flex overflow-hidden flex-1 shrink my-auto rounded basis-0 bg-stone-300 min-h-[8px] min-w-[240px]">
        <div
          className="flex flex-1 shrink w-full bg-orange-500 rounded basis-0 min-h-[8px]"
          style={{ width: `${percentage}%` }}
        />
      </div>
      <div className="w-10 text-right text-stone-500">{percentage}%</div>
    </div>
  );
};

export default ReviewBar;
