/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StarRating from "./StarRating";

interface ReviewItemProps {
  name: string;
  date: string;
  rating: number;
  comment: string;
}

const ReviewItem: React.FC<ReviewItemProps> = ({
  name,
  date,
  rating,
  comment,
}) => {
  return (
    <article className="flex overflow-hidden flex-col justify-center p-4 w-full bg-stone-50 max-md:max-w-full">
      <div className="flex flex-col w-full bg-stone-50 max-md:max-w-full">
        <div className="flex flex-col flex-1 w-full max-md:max-w-full">
          <h3 className="w-full text-base font-medium whitespace-nowrap text-stone-900 max-md:max-w-full">
            {name}
          </h3>
          <time className="w-full text-sm text-stone-500 max-md:max-w-full">
            {date}
          </time>
        </div>
        <StarRating rating={rating} />
        <p className="mt-3 w-full text-base text-stone-900 max-md:max-w-full">
          {comment}
        </p>
        <div className="flex flex-wrap gap-9 items-start mt-3 w-full max-md:max-w-full">
          <button
            className="flex gap-2 items-center w-5"
            aria-label="Like review"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/32e9bb0446b989c876ae00289fb70ca95e691e23f21daa53b730f502b0af034f?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea"
              alt=""
              className="object-contain flex-1 w-5 aspect-square"
            />
          </button>
          <button
            className="flex gap-2 items-center w-5"
            aria-label="Dislike review"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/14d0421a8a775a9a53d5ed736fadbc4f12210788134a27c65ef819fb267d3014?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea"
              alt=""
              className="object-contain flex-1 w-5 aspect-square"
            />
          </button>
        </div>
      </div>
    </article>
  );
};

export default ReviewItem;
