/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StarRatingProps {
  rating: number;
}

const StarRating: React.FC<StarRatingProps> = ({ rating }) => {
  return (
    <div className="flex gap-0.5 items-start mt-2">
      {[1, 2, 3, 4, 5].map((star) => (
        <div key={star} className="flex flex-col w-[18px]">
          <img
            loading="lazy"
            src={`http://b.io/ext_${star}-`}
            alt=""
            className="object-contain flex-1 aspect-square w-[18px]"
          />
        </div>
      ))}
    </div>
  );
};

export default StarRating;
