/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DurationSection: React.FC = () => {
  return (
    <section className="flex flex-col w-full">
      <h2 className="px-4 pt-4 pb-2 w-full text-lg font-bold leading-none whitespace-nowrap text-stone-900">
        Duration
      </h2>
      <div className="flex flex-col flex-1 justify-between p-4 w-full">
        <div className="w-full text-base font-medium text-stone-900">
          0 - 60 min
        </div>
        <div className="flex items-start pt-1.5 mt-3 w-full min-h-[38px]">
          <div className="flex flex-1 shrink items-start pr-11 pl-44 w-full rounded-sm basis-0 bg-stone-300 min-h-[4px] min-w-[240px] max-md:px-5">
            <div className="flex flex-1 shrink w-full bg-orange-500 rounded-sm basis-0 min-h-[4px]" />
          </div>
        </div>
      </div>
    </section>
  );
};

export default DurationSection;
