/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FilterSection from "./FilterSection";
import SortBySection from "./SortBySection";
import DurationSection from "./DurationSection";

interface FilterOption {
  label: string;
  isSelected: boolean;
}

const FilterContainer: React.FC = () => {
  const filterOptions: FilterOption[] = [
    { label: "Recipe", isSelected: true },
    { label: "Video", isSelected: false },
    { label: "Article", isSelected: false },
    { label: "User", isSelected: false },
  ];

  const timeOptions: FilterOption[] = [
    { label: "All time", isSelected: true },
    { label: "Today", isSelected: false },
    { label: "This week", isSelected: false },
    { label: "This month", isSelected: false },
    { label: "This year", isSelected: false },
  ];

  const sortOptions: FilterOption[] = [
    { label: "Relevance", isSelected: true },
    { label: "Most view", isSelected: false },
    { label: "Most like", isSelected: false },
    { label: "Newest", isSelected: false },
  ];

  return (
    <aside className="flex overflow-hidden flex-col w-80 min-w-[240px]">
      <FilterSection title="Filter" options={filterOptions} />
      <FilterSection title="" options={timeOptions} />
      <SortBySection options={sortOptions} />
      <DurationSection />
    </aside>
  );
};

export default FilterContainer;
