/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FilterOption from "./FilterOption";

interface FilterSectionProps {
  title: string;
  options: Array<{ label: string; isSelected: boolean }>;
}

const FilterSection: React.FC<FilterSectionProps> = ({ title, options }) => {
  return (
    <section className="flex flex-col p-4 w-full">
      {title && (
        <h2 className="px-4 pt-4 pb-2 w-full text-lg font-bold leading-none whitespace-nowrap text-stone-900">
          {title}
        </h2>
      )}
      {options.map((option, index) => (
        <FilterOption
          key={index}
          label={option.label}
          isSelected={option.isSelected}
        />
      ))}
    </section>
  );
};

export default FilterSection;
