/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FilterOption from "./FilterOption";

interface SortBySectionProps {
  options: Array<{ label: string; isSelected: boolean }>;
}

const SortBySection: React.FC<SortBySectionProps> = ({ options }) => {
  return (
    <section className="flex flex-col p-4 w-full">
      <h2 className="px-4 pt-4 pb-2 w-full text-lg font-bold leading-none text-stone-900">
        Sort by
      </h2>
      {options.map((option, index) => (
        <FilterOption
          key={index}
          label={option.label}
          isSelected={option.isSelected}
        />
      ))}
    </section>
  );
};

export default SortBySection;
