/**
 * This code was generated by Builder.io.
 */
import React from "react";
import IngredientItem from "./IngredientItem";

interface Ingredient {
  image: string;
  description: string;
}

const ingredients: Ingredient[] = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4c5cd77f788388884224c0e89029d284e19ec2fd610cd6a7f87a7f361a8f42f7?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "1/4 cup olive oil",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/85aa93b608bc33084171d1d6d54f3b032fdfa9e6ff2b54716921ba4efd406b7d?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "1/4 cup lemon juice",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/a0e3d50d8ee332bb9c9f3460ca6b21e37a351574393adc1b3088b880bc595d9b?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "2 cloves garlic, minced",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/72f478592aac5ff03a174baab59b199680ecef451787f0abb5ae0fff04b40a95?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "1 teaspoon dried oregano",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/d3af6ccc31650a4e26d358056309a9919433cbd8b19aac4817253f1427ec6b9f?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "1 teaspoon dried basil",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4fae679eb919cf4d5c4a22e5527ecf41d3d7ece135d9bc23be66fade55f9a663?placeholderIfAbsent=true&apiKey=4acd4cdcb7dc4d7e9af8a5ed4cd634ea",
    description: "1/2 teaspoon salt",
  },
];

const IngredientList: React.FC = () => {
  return (
    <section className="box-border flex relative flex-col shrink-0">
      <h2 className="px-4 pt-5 pb-3 w-full text-2xl font-bold leading-none whitespace-nowrap text-stone-900 max-md:max-w-full">
        Ingredients
      </h2>
      <ul className="flex flex-col px-4 w-full text-base text-stone-900 max-md:max-w-full">
        {ingredients.map((ingredient, index) => (
          <IngredientItem
            key={index}
            image={ingredient.image}
            description={ingredient.description}
          />
        ))}
      </ul>
    </section>
  );
};

export default IngredientList;
