/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface IngredientItemProps {
  image: string;
  description: string;
}

const IngredientItem: React.FC<IngredientItemProps> = ({
  image,
  description,
}) => {
  return (
    <li className="flex flex-wrap gap-3 items-start py-3 w-full max-md:max-w-full">
      <img
        loading="lazy"
        src={image}
        alt=""
        className="object-contain shrink-0 w-5 rounded aspect-square"
      />
      <div className="w-[203px]">{description}</div>
    </li>
  );
};

export default IngredientItem;
