/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Breakfast from "./Breakfast";

const App: React.FC = () => {
  return (
    <main>
      <Breakfast title="Breakfast" />
    </main>
  );
};

export default App;
