/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InstructionItemProps {
  text: string;
}

const InstructionItem: React.FC<InstructionItemProps> = ({ text }) => {
  return (
    <li className="flex gap-4 items-center px-4 w-full text-base bg-stone-50 min-h-[56px] text-stone-900 max-md:max-w-full">
      <div className="overflow-hidden flex-1 shrink self-stretch my-auto w-full min-w-[240px] max-md:max-w-full">
        {text}
      </div>
    </li>
  );
};

export default InstructionItem;
