/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import IngredientTags from "./IngredientTags";
import RecipeGrid from "./RecipeGrid";
import Pagination from "./Pagination";

const RecipeSearch: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col flex-1 shrink basis-0 max-w-[960px] min-w-[240px] max-md:max-w-full">
      <header className="flex flex-wrap gap-3 justify-between items-start p-4 w-full max-md:max-w-full">
        <div className="flex flex-col min-w-[288px] w-[352px]">
          <h1 className="max-w-full text-3xl font-bold leading-none text-stone-900 w-[352px]">
            What's in your fridge?
          </h1>
          <p className="mt-3 max-w-full text-sm text-stone-500 w-[352px]">
            We'll find the recipes for you
          </p>
        </div>
        <SearchBar />
      </header>
      <IngredientTags />
      <RecipeGrid />
      <Pagination />
    </main>
  );
};

export default RecipeSearch;
