/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface RecipeCardProps {
	image: string;
	title: string;
	time: string;
	rating: string;
	reviews: string;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ image, title }) => (
	<article className="flex flex-col shrink pb-3 w-[25%]">
		<img
			loading="lazy"
			src={image}
			alt={title}
			className="object-contain rounded-xl aspect-square w-[100%]"
		/>
		<div className="flex flex-col mt-[-20px] w-full">
			<h3 className="w-full text-base font-medium text-stone-900">{title}</h3>
			<p className="w-full text-sm text-stone-500">
				{Math.floor(Math.random() * 60) + 1 + "min"} ·{" "}
				{Math.floor(Math.random() * 5) + 1} ☆ (1.
				{Math.floor(Math.random() * 5) + 1}k)
			</p>
		</div>
	</article>
);

interface RecipeGridProps {
	recipes: any[] | null;
}

const RecipeGrid: React.FC<RecipeGridProps> = ({ recipes }) => {
	console.log(recipes);
	return (
		<section className="flex flex-col p-4 w-full max-md:max-w-full">
			<div className="flex flex-wrap gap-3 items-start w-full max-md:max-w-full">
				{recipes?.map((recipe, index) => (
					<RecipeCard key={index} {...recipe} />
				))}
			</div>
		</section>
	);
};

export default RecipeGrid;
