/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <form className="flex overflow-hidden justify-center items-center px-4 text-sm font-medium text-center whitespace-nowrap rounded-xl bg-stone-200 max-w-[480px] min-h-[32px] min-w-[84px] text-stone-900 w-[84px]">
      <label htmlFor="searchInput" className="sr-only">
        Search
      </label>
      <input
        type="search"
        id="searchInput"
        className="overflow-hidden self-stretch my-auto w-[50px] bg-transparent border-none focus:outline-none"
        placeholder="Search"
        aria-label="Search"
      />
    </form>
  );
};

export default SearchBar;
