/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InstructionItem from "./InstructionItem";

interface Instruction {
  text: string;
}

const instructions: Instruction[] = [
  {
    text: "Whisk olive oil, lemon juice, garlic, oregano, basil, and salt together in a bowl until dressing is smooth.",
  },
  {
    text: "Combine cucumber, tomatoes, onion, bell pepper, and olives in a large bowl.",
  },
  {
    text: "Pour dressing over vegetables; toss to coat. Add feta cheese and toss gently. Let stand for 10 minutes before serving.",
  },
];

const Instructions: React.FC = () => {
  return (
    <section className="box-border flex relative flex-col shrink-0">
      <h2 className="px-4 pt-5 pb-3 w-full text-2xl font-bold leading-none whitespace-nowrap text-stone-900 max-md:max-w-full">
        Instructions
      </h2>
      <ol className="box-border flex relative flex-col shrink-0">
        {instructions.map((instruction, index) => (
          <InstructionItem key={index} text={instruction.text} />
        ))}
      </ol>
    </section>
  );
};

export default Instructions;
