/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface RatingProps {
  rating: number;
  ratingCount: number;
}

const Rating: React.FC<RatingProps> = ({ rating, ratingCount }) => {
  return (
    <div className="w-full max-md:max-w-full">
      {rating.toFixed(1)} ({ratingCount} rating{ratingCount !== 1 ? "s" : ""})
    </div>
  );
};

export default Rating;
