/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface RecipeDetailsProps {
  cookTime: string;
  servings: number;
  caloriesPerServing: number;
}

const RecipeDetails: React.FC<RecipeDetailsProps> = ({
  cookTime,
  servings,
  caloriesPerServing,
}) => {
  return (
    <div className="mt-1 w-full max-md:max-w-full">
      {cookTime} · {servings} servings · {caloriesPerServing} calories per
      serving
    </div>
  );
};

export default RecipeDetails;
