/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Rating from "./Rating";
import RecipeDetails from "./RecipeDetails";
import AddToMealPlanButton from "./AddToMealPlanButton";

interface RecipeCardProps {
  rating: number;
  ratingCount: number;
  title: string;
  cookTime: string;
  servings: number;
  caloriesPerServing: number;
  imageSrc: string;
}

const RecipeCard: React.FC<RecipeCardProps> = ({
  rating,
  ratingCount,
  title,
  cookTime,
  servings,
  caloriesPerServing,
  imageSrc,
}) => {
  return (
    <article className="flex flex-col justify-center p-4 w-full text-sm max-md:max-w-full">
      <div className="flex flex-wrap justify-between items-start w-full rounded-xl max-md:max-w-full">
        <div className="flex flex-col min-h-[171px] min-w-[240px] w-[608px] max-md:max-w-full">
          <div className="flex flex-col w-full text-stone-500 max-md:max-w-full">
            <Rating rating={rating} ratingCount={ratingCount} />
            <h2 className="mt-1 w-full text-base font-bold leading-none text-stone-900 max-md:max-w-full">
              {title}
            </h2>
            <RecipeDetails
              cookTime={cookTime}
              servings={servings}
              caloriesPerServing={caloriesPerServing}
            />
          </div>
          <AddToMealPlanButton />
        </div>
        <img
          loading="lazy"
          src={imageSrc}
          alt={`${title} recipe`}
          className="object-contain flex-1 shrink w-full rounded-xl aspect-[1.87] basis-0 min-w-[240px]"
        />
      </div>
    </article>
  );
};

export default RecipeCard;
