/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AddToMealPlanButton: React.FC = () => {
  return (
    <button className="flex overflow-hidden justify-center items-center px-4 mt-4 max-w-full font-medium text-center rounded-xl bg-stone-200 min-h-[32px] min-w-[84px] text-stone-900 w-[149px]">
      <span className="overflow-hidden self-stretch my-auto w-[117px]">
        Add to meal plan
      </span>
    </button>
  );
};

export default AddToMealPlanButton;
