/**
 * This code was generated by Builder.io.
 */
import React from "react";
import RecipeCard from "./RecipeCard";

interface Recipe {
  imageSrc: string;
  title: string;
}

interface RecipeSectionProps {
  title: string;
  recipes: Recipe[];
}

const RecipeSection: React.FC<RecipeSectionProps> = ({ title, recipes }) => {
  return (
    <section className="w-full max-md:max-w-full">
      <h2 className="px-4 pt-5 pb-3 w-full text-2xl font-bold leading-none text-stone-900 max-md:max-w-full">
        {title}
      </h2>
      <div className="flex flex-col p-4 w-full text-base font-medium text-stone-900 max-md:max-w-full">
        <div className="flex flex-wrap flex-1 gap-3 size-full max-md:max-w-full">
          {recipes.map((recipe, index) => (
            <RecipeCard
              key={index}
              imageSrc={recipe.imageSrc}
              title={recipe.title}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default RecipeSection;
