/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface RecipeCardProps {
  imageSrc: string;
  title: string;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ imageSrc, title }) => {
  return (
    <div className="flex flex-col grow shrink pb-3 w-[141px]">
      <img
        loading="lazy"
        src={imageSrc}
        alt={`${title} recipe`}
        className="object-contain w-44 rounded-xl aspect-[1.78]"
      />
      <div className="mt-3 w-full">{title}</div>
    </div>
  );
};

export default RecipeCard;
